baseURL = "https://dnguyenngoc.github.io/"
title = "Duy Nguyen"
theme = "wisdom"
languageCode = "en-us"
enableRobotsTXT = true
encoding = "UTF-8"
googleAnalytics = ''

[menu]
[[menu.main]]
  identifier = 'home'
  name = 'home'
  url = '/'
  weight = -110
[[menu.main]]
  identifier = 'posts'
  name = 'posts'
  url = '/posts/'
  weight = -100