baseURL = "https://dnguyenngoc.github.io/"
title = "Duy Nguyen"
theme = "wisdom"
languageCode = "en-us"
enableRobotsTXT = true
encoding = "UTF-8"
googleAnalytics = ''

[params]
  author = "Duy Nguyen"
  description =  "A blog by Duy Nguyen on technology and life."
  latestPostsLimit = 10
  hideReadingTime = true
  hideAuthor = true
  keywords = [ "technology", "programming" ]

[markup.goldmark.renderer]
  unsafe = true

[menu]
[[menu.main]]
  identifier = 'home'
  name = 'Home/ '
  url = '/'
  weight = -110
[[menu.main]]
  identifier = 'cv'
  name = 'Cv/ '
  url = '/cv/'
  weight = -100
[[menu.main]]
  identifier = 'posts'
  name = 'Posts/ '
  url = '/posts/'
  weight = -100
